    <div>
        <label>
            Имя
            <input type="text" name="user[name]" value="<?= isset($userData['name']) ? htmlspecialchars($userData['name']) : '' ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email
            <input type="email" name="user[email]" value="<?= isset($userData['email']) ? htmlspecialchars($userData['email']) : '' ?>">
        </label>
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Пароль
            <input type="password" name="user[password]">
        </label>
        <?php if (isset($errors['password'])): ?>
            <div><?= $errors['password'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Подтверждение пароля
            <input type="password" name="user[passwordConfirmation]" value="<?= isset($userData['passwordConfirmation']) ? htmlspecialchars($userData['passwordConfirmation']) : '' ?>">
        </label>
        <?php if (isset($errors['passwordConfirmation'])): ?>
            <div><?= $errors['passwordConfirmation'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Город
            <select name="user[city]">
                <option value="3">Москва</option>
                <option value="13">Пенза</option>
                <option value="399">Томск</option>
            </select>
        </label>
    </div>
