<?php if (count($flash) > 0): ?>
  <ul>
  <?php foreach ($flash as $messages): ?>
      <?php foreach ($messages as $message): ?>
          <li><?= $message ?></li>
      <?php endforeach ?>
  <?php endforeach ?>
  </ul>
<?php endif ?>


<table border="solid 1px">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>City</th>
    </tr>
    <?php foreach ($users as $user): ?>
    <tr>
        <td><?= "{$user['name']}" ?></td>
        <td><?= "{$user['email']}" ?></td>
        <td><?= "{$user['city']}" ?></td>
        <td>
            <form action="/users/<?= $user['id']?>/edit">
                <button>Edit</button>
            </form>
        </td>
        <td>
            <form action="/users/<?= $user['id']?>" method="post">
                <input type="hidden" name="_METHOD" value="DELETE">
                <button>Remove</button>
            </form>
        </td>
    </tr>
    <?php endforeach ?>
</table>
<br>
<form action="/users/new">
    <button>Create new User</button>
</form>